server:
  port: 8086

cshm:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      host: 139.159.150.134
      port: 3306
      database: cshm
      username: root
      password: long5812
  jwt:
    token-name: token
    admin-secret-key: admin-secret
    admin-ttl: 7200000
    user-secret-key: user-secret
    user-ttl: 7200000
  upload:
    path: ${user.dir}/upload/
    public-prefix: http://localhost:${server.port}


spring:
  main:
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${cshm.datasource.druid.driver-class-name}
    url: jdbc:mysql://${cshm.datasource.druid.host}:${cshm.datasource.druid.port}/${cshm.datasource.druid.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${cshm.datasource.druid.username}
    password: ${cshm.datasource.druid.password}
  sql:
    init:
      mode: never

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cshm.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      cshm:
        mapper: debug
        service: info
        controller: info
